name: Fetch Exchange Rates

on:
  schedule:
    # Setiap hari jam 09:44 WIB (02:44 UTC)
    - cron: '44 2 * * *'
  workflow_dispatch:

jobs:
  update-rates:
    runs-on: ubuntu-latest
    permissions:
      # Wajib untuk repo public agar bisa push
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch exchange rates
        run: |
          API_KEY="62f03ae7e5390aabb05cc7bafefd0336"
          curl "https://data.fixer.io/api/latest?access_key=$API_KEY" -o rates.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rates.json
          git commit -m "Update exchange rates" || echo "No changes to commit"
          git push
        env:
          # Pakai token bawaan GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
